### ISSUE TITLE
Swift 3.0 pointers support

### ISSUE THREAD

**Issue by ericmoreau** [n6xej/StructureScannerSwift#1]
Hi,
I'm not really good with pointers and it's my first issue on github, so apologies in advance
I've been playing with your port on Swift 3.0, everything is great so far but I've hit a wall with `withUnsafeMutablePointers(&currentProjection,
                                  &currentModelView,
                                  {
                                    renderer!.render(projectionMatrix: UnsafeMutablePointer<GLfloat>($0), modelViewMatrix: UnsafeMutablePointer<GLfloat>($1))
                                    }`
in meshviewcontroller draw() function
How would you manage to address the changes to pointers in Swift 3.0 using withMemoryRebound<T, Result> or whatever other techniques

Thanks,

E

**Comment by n6xej** [comment]
There was a change between Swift Beta 3 and the release, I think you have the old code. Check out a new version, it has been updated.
